[package]
name = "endorphin"
version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam = "0.8.1"
hashbrown = { version = "*", features = ["rayon", "raw"]}
once_cell = "1.8.0"
parking_lot = "0.11.2"
slotmap = "1.0.6"
smallvec = "1.7.0"
