[package]
name = "endorphin"
version = "0.1.0"
edition = "2018"

[dependencies]
hashbrown = { version = "*", features = ["rayon", "raw"]}
once_cell = "1.8.0"
parking_lot = "0.11.2"
ringbuffer = "0.8.3"
smallvec = "1.7.0"
